FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1
ENV PATH="/usr/local/bin:$PATH"

WORKDIR /app

COPY requirements.txt requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt 

COPY . .

ENV FLASK_APP=app.py

EXPOSE 5000

CMD ["python","-m","flask", "run", "--host=0.0.0.0", "--port=5000", "--debug"]
